#!/usr/bin/env php
<?php

$files = array(
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../autoload.php'
);

foreach ($files as $f) {
    if (file_exists($f)) {
        require_once $f;
        define("PREVIEW_INSTALLED", true);
        break;
    }
}

if (!defined("PREVIEW_INSTALLED")) {
    die("Preview is not correctly installed");
}

use \Preview\Configuration;
use \Preview\Loader;
use \Preview\World;
use \Preview\Reporter\Spec as SpecReporter;

Configuration::set_reporter(new SpecReporter);
// Preview\Configuration::set_assertion_error();

foreach ($argv as $arg) {
    (new Loader)->load($arg);
}

$results = World::run();

foreach($results as $result) {
    if ($result->error()) {
        exit(1);
    }
}
exit(0);
