#!/usr/bin/env php
<?php

/*
 * check preview files are autoloaded
 */
$files = array(
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../autoload.php'
);

foreach ($files as $f) {
    if (file_exists($f)) {
        require_once $f;
        define("PREVIEW_INSTALLED", true);
        break;
    }
}

if (!defined("PREVIEW_INSTALLED")) {
    die("Preview is not correctly installed");
}

/*
 * dependencies and const
 */
define("PREVIEW_CONFIG_FILE", "preview.config.php");

use \Preview\Preview;
use \Preview\World;
use \Preview\Configuration;
use \Preview\Loader;
use \Preview\Reporter\Spec as SpecReporter;

use Ulrichsg\Getopt;


/*
 * setup command line parser
 */
$cmd = new Getopt(
    array(
        array(
            "h", "help", Getopt::NO_ARGUMENT,
            "Show this help message."
        ),
        array(
            "r", "reporter", Getopt::REQUIRED_ARGUMENT,
            "Set reporter."
        ),
        array(
            "g", "group", Getopt::REQUIRED_ARGUMENT,
            "Test group(s). use comma(,) to seperate groups."
        ),
        array(
            "c", "config", Getopt::REQUIRED_ARGUMENT,
            "Load config file. Default './preview.config.php'."
        ),
        array(
            null, "no-this", Getopt::NO_ARGUMENT,
            'Disable using $this as an implicit context. PHP 5.4 only.'
        ),
        array(
            null, "no-color", Getopt::NO_ARGUMENT,
            "Disable color output."
        ),
        array(
            null, "with-error", Getopt::NO_ARGUMENT,
            "Disable converting error to exception."
        ),
        array(
            null, "list-groups", Getopt::NO_ARGUMENT,
            'List all the test groups.'
        ),
        array(
            null, "list-reporters", Getopt::NO_ARGUMENT,
            'List available reporters.'
        )
    )
);

$br = PHP_EOL;
$title = $br."    Preview ".Preview::$version.
    " - bdd test framework for php ".$br.$br;
$cmd->setTitle($title);
$cmd->parse();
$options = $cmd->getOptions();


/*
 * setup loader and test config, test world
 */
Preview::$world = new World;
Preview::$config = new Configuration;
$loader = new Loader;

/*
 * parse args, update config and load test files.
 */
$config_file = PREVIEW_CONFIG_FILE;
if (isset($options["config"])) {
    $config_file = $options["config"];
}

$config_file = realpath($config_file);
if (is_file($config_file)) {
    Preview::$config = Configuration::load_from_file($config_file);
}

// default reporter
if (!Preview::$config->reporter) {
    Preview::$config->reporter = new SpecReporter;
}

// Since for PHP version < 5.4 $this is not available for closure,
// We can't use this feature, instead we explicitly pass
// the context object as an argument to callback.
if (Preview::php_version_is_53()) {
    Preview::$config->use_implicit_context = false;
}

if (isset($options["help"])) {
    $cmd->showHelp();
    exit(0);
}

if (isset($options["list-reporters"])) {
    echo $title;
    $reporters = array("spec", "dropdown");
    foreach ($reporters as $index => $reporter) {
        $index = $index + 1;
        echo "    $index) $reporter$br";
    }
    echo $br;
    exit(0);
}

if (isset($options["reporter"])) {
    $reporter = "\\Preview\\Reporter\\{$options['reporter']}";
    Preview::$config->reporter = new $reporter;
}

if (isset($options["group"])) {
    Preview::$config->test_groups = explode(",", $options["group"]);
}

if (isset($options["no-this"])) {
    Preview::$config->use_implicit_context = false;
}

if (isset($options["no-color"])) {
    Preview::$config->color_support = false;
}

if (isset($options["with-error"])) {
    Preview::$config->error_exception = false;
}

$files = $cmd->getOperands();

// default help message
if (empty($options) and empty($files)) {
    $cmd->showHelp();
    exit(0);
}

// load all test file
foreach ($files as $file) {
    $loader->load($file);
}

// list groups
if (isset($options["list-groups"])) {
    echo $title;
    $groups = Preview::$world->groups();
    if (empty($groups)) {
        echo "    No test groups.$br$br";
        exit(0);
    }
    foreach ($groups as $index => $group) {
        $index = $index + 1;
        echo "    $index) $group$br";
    }
    echo $br;
    exit(0);
}


/*
 * run test and exit.
 */
$results = Preview::$world->run();
foreach($results as $result) {
    if ($result->error()) {
        exit(1);
    }
}

exit(0);